---
apiVersion: "apps/v1"
kind: "Deployment"
metadata: 
  name: "hqcloud-trigger"
  namespace: "kube-system"
  labels: 
    name: "hqcloud-trigger"
spec: 
  replicas: 1
  selector: 
    matchLabels:
      name: "hqcloud-trigger"
  template: 
    metadata: 
      labels: 
        name: "hqcloud-trigger"
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      containers:
      - name: "hqcloud-trigger"
        image: "registry.cn-beijing.aliyuncs.com/dosproj/hqcloud-trigger:v1.0.0-amd64"
        imagePullPolicy: "IfNotPresent"
        env:
        - name: kubeUrl
          value: https://127.0.0.1:6443
        - name: token
          value: xxx
        command: 
        - "java"
        - "-jar"
        - "hqcloud-trigger.jar"
---
apiVersion: v1
kind: Service
metadata:
  name: hqcloud-trigger
  namespace: kube-system
  labels: 
    name: hqcloud-trigger
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: hqcloud-trigger-port
    nodePort: 38080
  selector:
    name: hqcloud-trigger
