---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: algorithms.hqcloud.com
spec:
  additionalPrinterColumns:
  - JSONPath: .type
    name: type
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: created
    type: string
  group: hqcloud.com
  names:
    kind: Algorithm
    plural: algorithms
    singular: algorithm
  scope: Namespaced
  version: v1