---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: triggers.hqcloud.com
spec:
  additionalPrinterColumns:
  - JSONPath: .type
    name: type
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: created
    type: string
  group: hqcloud.com
  names:
    kind: Trigger
    plural: triggers
    singular: trigger
  scope: Namespaced
  version: v1